volumes:
  prometheus_data: {}

services:
  web:
    image: python3-server:testing
    ports:
      - 1234:1234
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/src/:/home/ubuntu/project/code/
    command: [ "python3", "-u", "code/python-server.py" ]

  prom:
    image: prom/prometheus
    volumes:
      - ./prom/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prom.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  alert:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./prom/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'
